### PR TITLE
Adding environment variables to Jenkinsfile

### PR DESCRIPTION
**Pull request by lilesj**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nixnet-python/blob/master/CONTRIBUTING.rst).
- [ ] New tests have been created for any new features or regression tests for bugfixes.
- [x] `tox` successfully runs, including unit tests and style checks (see [CONTRIBUTING.md](https://github.com/ni/nixnet-python/blob/master/CONTRIBUTING.rst)).

### What does this Pull Request accomplish?

Established environment variables in the Jenkinsfile to specify hardware for CI testing.

### Why should this Pull Request be merged?

To enable CI testing with hardware.

### What testing has been done?

Verified Jenkins executes test script on my dev fork.

### CODE REVIEW

**Comment by epage** [comment]
py2-test failed because of #116.  I'm working on a fix for that but it does raise the question, why are we running the tests on Python 2.7.0 instead of the latest Python 2.7 release?

Granted, the latest python release is also broken, see #127.  My fix will hopefully fix both.

**Comment by lilesj** [comment]
I installed 2.7.0 because it is the earliest version that we claimed to support at the time of setup. It looks like we have since modified our claimed support to 2.7.7 so I can update the test machine accordingly.

**Comment by epage** [comment]
Previously, I was only aware of us claiming 2.7.  I guess the question is does that presume the latest or earliest 2.7.

**Comment by epage** [comment]
I'm confirming with our other python projects for consistency purposes.

When we decided on Python 2.7 support, I presume Python 2.7.<latest> because those dot-releases are bug fixes and we should only guarantee support with all the latest bug fixes, similar to when an SP1 of LabVIEW comes out, we stop supporting the non-SP1 (I think).

**Pull request merged**
